[theme]
primaryColor = "#2E74B5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#1F3964"
font = "sans serif"

[server]
maxUploadSize = 50
enableXsrfProtection = true
headless = true
address = "0.0.0.0"
port = 8501

[browser]
gatherUsageStats = false
